apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openbao-system
configMapGenerator:
  - name: openbao-kubernetes-auth-bootstrap
    files:
      - bootstrap.sh
      - external-secrets-openbao.hcl
    options:
      disableNameSuffixHash: true
resources:
  - rbac.yaml
  - job.yaml
