apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/demo-app/
  - image-automation.yaml
images:
  - name: ghcr.io/alissonmmenezes/demo-app # {"$imagepolicy": "flux-system:demo-app:name"}
    newTag: 0.1.8 # {"$imagepolicy": "flux-system:demo-app:tag"}
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: demo-api
      namespace: app-dev
    path: ingress-dev-patch.yaml
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: demo-app-db
      namespace: app-dev
    path: postgres-instances-patch.yaml
