apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-app-postgres
  namespace: app-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: demo-app-postgres
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_USER
      remoteRef:
        key: demo-app/postgres
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: demo-app/postgres
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: demo-app/postgres
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: demo-app/postgres
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: demo-app/postgres
        property: dbname
