apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clustersecretstore-openbao.yaml
  - postgres-cluster.yaml
  - pushsecret-cnpg-to-openbao.yaml
  - externalsecret-demo-app-postgres.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - network-policy-demo-api-allow.yaml
  - ingress.yaml
  - servicemonitor.yaml
